-- MekBits fork only: Realm First! Level 80 Goblin (1429) and Worgen (1430)
-- had the level in Asset_Id and 0 in Quantity (workflow/achievement_criteria_dbc.sql).
-- AzerothCore reads the level from Quantity, so the criteria were met at level
-- 0: every goblin and worgen character got the achievement when it was created,
-- and nobody can earn it now. The criteria now ask for level 80; this clears
-- the completions and the progress the broken criteria left, so the first
-- goblin and worgen to reach 80 get them.
--
-- Do not edit this file. The updater re-runs a changed file in full, and that
-- would clear the completions earned honestly since.
DELETE FROM `character_achievement` WHERE `achievement` IN (1429, 1430);
DELETE FROM `character_achievement_progress` WHERE `criteria` IN (13477, 13478);
